name: beep
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  fl_country_code_picker: ^0.0.4
  fluttertoast: ^8.2.12
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.2
  socket_io_client: ^3.0.2
  intl: ^0.20.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/animation/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 23
  remove_alpha_ios: true
